import Head from 'next/head'
import AboutMe from '../components/aboutMe/AboutMe'
import Header from '../components/Header/Header'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio - Cássio Rodrigues</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <Header />
      <AboutMe />
    </div>
)}
