import { useEffect } from 'react'
import Head from 'next/head'
import AboutMe from '../components/aboutMe/AboutMe'
import Header from '../components/Header/Header'
import MyProjects from '../components/myProjects/MyProjects'
import AOS from 'aos'
import 'aos/dist/aos.css'

export default function Home() {
  useEffect(() => {
    AOS.init()
    
  }, [])
  return (
    <div>
      <Head>
        <title>Portfolio - Cássio Rodrigues</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <AboutMe />
      <MyProjects />
    </div>
)}